### ISSUE TITLE
Toggle button doesn't work

### ISSUE THREAD

**Issue by rivalsystems** [cosmocode/dokuwiki-plugin-prosemirror#121] opened 2020-08-20 16:51 UTC
Tried the 7-26 version and also the 8-20-2020 release.

I'm using Argon template. The Toggle button doesn't do anything when i click it. Running the hogfather RC3 at the moment

**Comment by 0x4a** [comment] 2020-11-12 22:32
I have the same problem, nothing does load.
Tried deactivating defer_js, but did not change anything...


Running Prosemirror 2020-10-01 on Hogfather 2020-07-29.

How would I go about helping to debug this @cosmocode?

**Comment by Openuser87** [comment] 2021-01-31 19:49
Same here with Argon plugin. Works with default and bootstrap3, however.

Any chance for a fix or a workaround?

**Comment by kl0wn** [comment] 2021-02-24 14:43
Not working here either, Hogfather 2020-07-29 2020-10-01.

Toggle button appears but does nothing when clicked

**Comment by Klap-in** [comment] 2021-02-24 17:42
@kl0wn which template are you using? Or other relevant info which might be needed to reproduce your situation.

**Comment by kl0wn** [comment] 2021-02-25 14:18
> @kl0wn which template are you using? Or other relevant info which might be needed to reproduce your situation.

I'm using default template.

After restarting the server for another issue the toggle button worked correctly so...I guess my issue is resolved

**Comment by annda** [comment] 2022-01-05 15:49
I'm closing this issue because the problem description is too generic.

**Closed by annda** 2022-01-05 15:49 UTC
