### ISSUE TITLE
Empty headings break the plugin

### ISSUE THREAD

**Issue by jorbig** [cosmocode/dokuwiki-plugin-prosemirror#105] opened 2020-02-24 15:55 UTC
When someone accidentally inserts a heading and then saves the page without typing anything, the Prosemirror editor won't load anymore. In other words: the Prosemirror editor is broken and won't load when the DW editor shows something like this on a page:
`====  ====`

**Comment by jorbig** [comment] 2020-09-30 21:58
A half year later, this issue is still not fixed. The error shown with empty headings (only containing a space) is:

`There was an error in the WYSIWYG editor. You will be redirected to the syntax editor in 5 seconds.`

**Comment by vic-t** [comment] 2021-04-30 19:30
Out of sheer curiosity, I tried to reproduce the described issue. 

Yes, if in DW Editor mode you enter an empty heading by _manually typing the equal signs and the space in between,_ you will get the error message you described when toggling to WYSIWYG mode. Note, though, that when using the toolbar in the DW Editor to create a heading, you cannot enter an empty heading by accident since the sample text "Headline" is put between the equal signs. 

Also, I have not found a way to create an empty heading from within the WYSIWYG editor. I tried creating a header with no space, with one space, with several spaces, it simply won't save and thus won't break the editor. 

If your experience was different when you reported the issue, then it would seem this was fixed in the meantime.

**Comment by jorbig** [comment] 2021-08-03 09:01
@vic-t sorry for my late reply, but the bug is still there. Reproduce it by doing this:

1. Edit a page in WYSIWYG mode (eg. https://wysiwyg.wiki.cosmocode.de/doku.php?id=en:playground:start&do=edit)
2. Add a heading from the Prosemirror menubar (eg. Heading 2).
3. If you don't type anything but save right away, it shows the errors.

**Comment by vic-t** [comment] 2021-08-03 09:28
Hi @jorbig, 

I understood your report and that's exactly what I'm doing: I'm opening a page to edit in WYSIWYG mode, I add a heading from the menubar without typing anything, then I press save: I get no errors and the empty heading is not saved. 

I tried it in my own wiki as well as in the prosemirror plugin playground with the exact same result. 

If you're experience is different, maybe it's a question of the browser and/or plugins used? Try it with a fresh install or portable version of Firefox and see if you can still reproduce the issue.

**Comment by jorbig** [comment] 2021-08-03 09:44
@vic-t This is strange: 40 minutes ago I was able to reproduce the error (in different browsers) using the official playground, but now I'm not able to reproduce it at all. I can't wrap my head around this.

**Closed** 2021-08-03 09:44 UTC

**Comment by vic-t** [comment] 2021-08-03 10:33
Strange indeed. I guess you can monitor this and come back anytime to reopen the issue if necessary. By then you may have an idea about the cause.
